---
name: Bug report (**search and look at the pinned issues before filing**)
description: >
  Bugs related to the NDK itself. ndk-build, CMake toolchain file, sysroot, etc.
title: "[BUG]"
labels: bug
body:
  - type: markdown
    attributes:
      value: >
        Before filing a bug, check that you are using the latest version of the
        NDK. The latest stable version and the preview release of the next
        stable version are listed on our wiki:
        https://github.com/android-ndk/ndk/wiki#downloads.


        Make sure your issue isn't on the list of common problems before filing
        a bug:
        https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Describe the bug. Include a test case. It's unlikely that anything can be done without a test case.

        Bug reports with better test cases will be resolved sooner than those with bad test cases. A good test case:

        * Is as small as possible while still exposing the bug.
        * Does not require Android Studio or Gradle. If your bug cannot be reproduced without either of those, it's a bug in Studio or Gradle, and should be reported to Android Studio.
        * Is complete. Snippets that would not compile even in the absence of the bug you are reporting slow down the process.

        Here's an example of a good test case: https://github.com/DanAlbert/dynamic-cast-repro

        Some ways to include test cases:

        * Linking to another git repo with build instructions (preferred)
        * Attaching a zip or tarball to this bug by dragging and dropping into the description text box
        * Linking to a gist
        * Including the full text of the text case here (please use a gist for longer test cases)
  - type: checkboxes
    id: supported
    attributes:
      label: I am using a supported NDK
      description: >
        If you're using an unsupported NDK, don't file the bug. We will only
        investigate bugs that impact supported NDKs.
      options:
        - label: I have checked and the NDK I'm using is currently supported
          required: true
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Affected versions
      multiple: true
      description: >
        **If you are using Unity, double check the NDK version you're using.
        It's probably not in this list because it's not supported. File those
        bugs with Unity.**


        Select all NDK versions in which you have observed this bug. **NDK
        versions not listed here are not supported and those bugs will be closed
        without investigation.**
        
        
        If you're not sure which NDK version you're using, check
        the `android.ndkVersion` for your AGP project, or look in
        `$NDK/source.properties`.


        If the bug was found in a canary build of the NDK, pick either, but use
        the bug description to say so, and include the ci.android.com build
        number.
      options:
        - r27
        - r28
